// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MomAndChildren.Data.Models;

public partial class OrderDetail
{
    public int OrderDetailId { get; set; }

    public double UnitPrice { get; set; }

    public double TotalPrice { get; set; }

    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public long Quantity { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }
}