// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MomAndChildren.Data.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public double TotalPrice { get; set; }

    public int CustomerId { get; set; }

    public DateTime OrderDate { get; set; }

    public int TotalQuantity { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ICollection<PaymentHistory> PaymentHistories { get; set; } = new List<PaymentHistory>();
}